GET http://localhost:8080/v1/video-games?name=Super&genre=Fighting
Accept: application/json

###
GET http://localhost:8080/v1/video-games?name=Super&genre=Platform
Accept: application/json

###
GET http://localhost:8080/v2/video-games
Accept: application/json

###
GET http://localhost:8080/v3/video-games?sales=1000
Accept: application/json

###
GET http://localhost:8080/v3/video-games?sales=5000
Accept: application/json

###
POST http://localhost:8080/v1/video-game-publishers
Content-Type: application/json

{
  "name": "Microsoft",
  "location": "United States"
}

###
POST http://localhost:8080/v2/video-game-publishers
Content-Type: application/json

{
  "name": "Microsoft",
  "location": "Japan"
}

###
DELETE http://localhost:8080/v1/video-game-publishers/5
Content-Type: application/json
